name: btrfs_toolkit
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  ansicolor: ^2.0.3

# Add dev dependencies here.
  # path: ^1.8.0
